In [1]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')

In [2]:
df1 = pd.read_parquet('../DATASETS/fugas_2021.parquet')
df1.head()

,folio,tipo_de_falla,quien_atiende,latitud,longitud,codigo_postal,fecha,colonia_registro_sacmex,colonia_datos_abiertos,alcaldia
0,20210107-0129,Fuga,Tláhuac,19.310192,-99.047786,NaN,2021-01-07,Ciudad de México,LAS ARBOLEDAS,TLAHUAC
1,20210101-0008,Fuga,Iztapalapa,19.370615,-99.030413,9239.0,2021-01-01,Ciudad de México,EJERCITO DE ORIENTE (U HAB) I,IZTAPALAPA
2,20210101-0020,Fuga,Álvaro Obregón,19.375857,-99.233819,NaN,2021-01-01,Ciudad de México,2DA JALALPA TEPITO (AMPL),ALVARO OBREGON
3,20210101-0048,Fuga,Álvaro Obregón,19.388433,-99.201850,1150.0,2021-01-01,Colonia Cristo Rey,CRISTO REY,ALVARO OBREGON
4,20210101-0049,Fuga,Azcapotzalco,19.473759,-99.176527,2060.0,2021-01-01,Un Hogar Para Cada Trabajador,UN HOGAR PARA CADA TRABAJADOR,AZCAPOTZALCO

In [3]:
df2 = pd.read_parquet('../DATASETS/fugas_2022-2024.parquet')
df2['fecha_registro_incidente'] = pd.to_datetime(df2['fecha_registro_incidente'])
df2['fecha_reporte'] = pd.to_datetime(df2['fecha_reporte'])
df2.head()

,folio,fecha_registro_incidente,id_reporte,fecha_reporte,hora_reporte,clasificacion,tipo_de_falla,medio_recepcion,alcaldia_catalogo,colonia_catalogo,latitud,longitud
0,I-20220101-0001,2022-01-02,R-20220101-0105,2022-01-01,18:33:08,Agua Potable,Fuga,Ciudadano (Call Center),Coyoacán,Cuadrante De San Francisco,19.341800,-99.168273
1,I-20220101-0003,2022-01-02,R-20220101-0103,2022-01-01,18:12:39,Agua Potable,Fuga,Ciudadano (Call Center),Tláhuac,Barrio Santiago Norte Del Pueblo Santiago Zapo...,19.300514,-99.030287
2,I-20220101-0004,2022-01-02,R-20220101-0108,2022-01-01,19:01:39,Agua Potable,Fuga,Ciudadano (Call Center),NA,NA,19.543890,-99.154970
3,I-20220101-0006,2022-01-02,R-20220101-0111,2022-01-01,19:10:41,Agua Potable,Fuga,Ciudadano (Call Center),Álvaro Obregón,Florida,19.360753,-99.179922
4,I-20220101-0008,2022-01-02,R-20221204-0151,2022-12-04,17:51:20,Agua Potable,Fuga,Ciudadano (Call Center),Tlalpan,Miguel Hidalgo 4a Seccion,19.273899,-99.207036

In [4]:
df3 = pd.DataFrame([])
df3['folio'] = df1['folio']
df3['fecha_registro_incidente'] = None
df3['id_reporte'] = pd.NA
df3['fecha_reporte'] = pd.to_datetime(df1['fecha'])
df3['hora_reporte'] = pd.NA
df3['clasificacion'] = 'Agua Potable'
df3['tipo_de_falla'] = df1['tipo_de_falla']
df3['medio_recepcion'] = 'Ciudadano (Call Center)'
df3['alcaldia_catalogo'] = df1['alcaldia'].str.upper()
df3['colonia_catalogo'] = df1['colonia_datos_abiertos'].str.upper()
df3['latitud'] = df1['latitud']
df3['longitud'] = df1['longitud']
df3.head()

,folio,fecha_registro_incidente,id_reporte,fecha_reporte,hora_reporte,clasificacion,tipo_de_falla,medio_recepcion,alcaldia_catalogo,colonia_catalogo,latitud,longitud
0,20210107-0129,None,<NA>,2021-01-07,<NA>,Agua Potable,Fuga,Ciudadano (Call Center),TLAHUAC,LAS ARBOLEDAS,19.310192,-99.047786
1,20210101-0008,None,<NA>,2021-01-01,<NA>,Agua Potable,Fuga,Ciudadano (Call Center),IZTAPALAPA,EJERCITO DE ORIENTE (U HAB) I,19.370615,-99.030413
2,20210101-0020,None,<NA>,2021-01-01,<NA>,Agua Potable,Fuga,Ciudadano (Call Center),ALVARO OBREGON,2DA JALALPA TEPITO (AMPL),19.375857,-99.233819
3,20210101-0048,None,<NA>,2021-01-01,<NA>,Agua Potable,Fuga,Ciudadano (Call Center),ALVARO OBREGON,CRISTO REY,19.388433,-99.201850
4,20210101-0049,None,<NA>,2021-01-01,<NA>,Agua Potable,Fuga,Ciudadano (Call Center),AZCAPOTZALCO,UN HOGAR PARA CADA TRABAJADOR,19.473759,-99.176527

In [5]:
# Join

df_general = pd.concat([df3, df2])

In [6]:
df_general

,folio,fecha_registro_incidente,id_reporte,fecha_reporte,hora_reporte,clasificacion,tipo_de_falla,medio_recepcion,alcaldia_catalogo,colonia_catalogo,latitud,longitud
0,20210107-0129,NaT,NaN,2021-01-07,NaN,Agua Potable,Fuga,Ciudadano (Call Center),TLAHUAC,LAS ARBOLEDAS,19.310192,-99.047786
1,20210101-0008,NaT,NaN,2021-01-01,NaN,Agua Potable,Fuga,Ciudadano (Call Center),IZTAPALAPA,EJERCITO DE ORIENTE (U HAB) I,19.370615,-99.030413
2,20210101-0020,NaT,NaN,2021-01-01,NaN,Agua Potable,Fuga,Ciudadano (Call Center),ALVARO OBREGON,2DA JALALPA TEPITO (AMPL),19.375857,-99.233819
3,20210101-0048,NaT,NaN,2021-01-01,NaN,Agua Potable,Fuga,Ciudadano (Call Center),ALVARO OBREGON,CRISTO REY,19.388433,-99.201850
4,20210101-0049,NaT,NaN,2021-01-01,NaN,Agua Potable,Fuga,Ciudadano (Call Center),AZCAPOTZALCO,UN HOGAR PARA CADA TRABAJADOR,19.473759,-99.176527
...,...,...,...,...,...,...,...,...,...,...,...,...
105617,I-20240131-0483,2024-02-01,R-20240201-0066,2024-02-01,08:36:05,Agua Potable,Fuga,Ciudadano (Call Center),Tlalpan,Maria Esther Zuno De Echeverria,19.259900,-99.175200
105618,I-20240131-0485,2024-02-01,R-20240131-0598,2024-01-31,22:01:45,Agua Potable,Fuga,Ciudadano (Call Center),Azcapotzalco,El Rosario,19.512400,-99.201900
105619,I-20240131-0489,2024-02-01,R-20240131-0605,2024-01-31,22:27:55,Agua Potable,Fuga,"C-5 (Protección Civil, Bomberos, Locatel)",Azcapotzalco,Nueva Santa Maria,19.470400,-99.167400
105620,I-20240131-0492,2024-02-01,R-20240131-0606,2024-01-31,22:31:30,Agua Potable,Fuga,Campamento o Alcaldía,Iztapalapa,Campestre Potrero,19.328200,-98.976800
105621,I-20240131-0493,2024-02-01,R-20240131-0609,2024-01-31,22:36:27,Agua Potable,Fuga,Campamento o Alcaldía,Iztapalapa,Constitucion De 1917,19.347400,-99.058000

In [7]:
df_general.info()

<class 'pandas.core.frame.DataFrame'>
Index: 138640 entries, 0 to 105621
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   folio                     138640 non-null  object
 1   fecha_registro_incidente  105622 non-null  datetime64[ns]
 2   id_reporte                105622 non-null  object
 3   fecha_reporte             138640 non-null  datetime64[ns]
 4   hora_reporte              105622 non-null  object
 5   clasificacion             138640 non-null  object
 6   tipo_de_falla             138640 non-null  object
 7   medio_recepcion           138640 non-null  object
 8   alcaldia_catalogo         138640 non-null  object
 9   colonia_catalogo          138640 non-null  object
 10  latitud                   138640 non-null  float64
 11  longitud                  138640 non-null  float64
dtypes: datetime64[ns](2), float64(2), object(8)
memory usage: 13.8+ MB

In [8]:
df_general.fecha_reporte.dt.year.unique()

array([2021, 2022, 2023, 2024])

In [9]:
df_general.to_parquet('../DATASETS/fugas.parquet.gzip', compression='gzip', index=False)